defaultRules:
  create: false

alertmanager:
  enabled: false

grafana:
  service:
    type: NodePort
    nodePort: 30100

prometheus:
  service:
    type: NodePort
    nodePort: 30200

prometheusOperator:
  tlsProxy:
    enabled: false
  tls:
    enabled: true

coreDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

#kubeStateMetrics:
#  enabled: true
#  image.repository:  k8s.gcr.io/kube-state-metrics/kube-state-metrics

#https://github.com/kubernetes/kube-state-metrics/blob/v1.9.7/Makefile

kube-state-metrics:
  image:
    repository: carlosedp/kube-state-metrics
    tag: v1.9.6
