defaultRules:
  create: false

alertmanager:
  enabled: false

grafana:
  service:
    type: NodePort
    nodePort: 30100

prometheus:
  service:
    type: NodePort
    nodePort: 30200

prometheusOperator:
  tlsProxy:
    enabled: false
  tls:
    enabled: true

coreDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

#kubeStateMetrics:
#  enabled: true
#  image.repository:  k8s.gcr.io/kube-state-metrics/kube-state-metrics

kube-state-metrics:
  image:
    repository: gcr.io/k8s-staging-kube-state-metrics/kube-state-metrics-arm64
