apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ddclient
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/speedwing/cardano-staking-pool-edu.git
    targetRevision: {{ .Values.git.targetRevision }}
    path: kubernetes/applications/ddclient

  destination:
    namespace: dnsutils
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    validate: true
