{{ range $attributes := .Values.nodes }}
{{ if $attributes.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "relay-node-{{ $attributes.name }}"
  labels:
    fix.me: fix-me!
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "relay-node-{{ $attributes.name }}"
  template:
    metadata:
      labels:
        app: "relay-node-{{ $attributes.name }}"
    spec:
      containers:
        - name: cardano-node
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          command: [ "cardano-node" ]
          args:
            - run
            - --topology
            - path/to/mainnet-topology.json
            - --database-path
            - /db
            - --socket-path
            - /db/node.socket
            - --host-addr
            - x.x.x.x
            - --port
            - {{ $attributes.port }}
            - --config
            - path/to/mainnet-config.json
          ports:
            - containerPort: {{ $attributes.port }}
{{ end }}
{{ end }}