{{ range $attributes := .Values.nodes }}
{{ if $attributes.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "relay-node-{{ $attributes.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "relay-node-{{ $attributes.name }}"
  template:
    metadata:
      labels:
        app: "relay-node-{{ $attributes.name }}"
    spec:
      containers:
        - name: cardano-node
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          command: [ "cardano-node" ]
          args:
            - "run"
            - "--topology"
            - "/etc/config/{{ $.Values.network }}-topology.json"
            - "--database-path"
            - "/db"
            - "--socket-path"
            - "/db/node.socket"
            - "--host-addr"
            - {{ $.Values.publicIp | quote }}
            - "--port"
            - {{ $attributes.port | quote }}
            - "--config"
            - "/etc/config/{{ $.Values.network }}-config.json"
          ports:
            - name: node
              containerPort: {{ $attributes.port }}
            - name: prom
              containerPort: {{ $attributes.prometheusPort | default 12798 }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: prom
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 10
          volumeMounts:
            - name: config-files
              mountPath: /etc/config
            - name: db
              mountPath: /db
      volumes:
        - name: config-files
          configMap:
            name: node-configuration-{{ $attributes.name }}
        - name: db
          persistentVolumeClaim:
            claimName: relay-node-alpha
  strategy:
    type: Recreate
{{ end }}
{{ end }}