---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-configuration
  labels:
    {{- include "cardano-relay-node.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "configuration/*.json").AsConfig | indent 2 }}
