---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: relay-node-alpha
  labels:
    {{- include "cardano-relay-node.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi