{{ range $attributes := .Values.nodes }}
{{ if $attributes.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: cardano-node-{{ $attributes.name }}
spec:
  selector:
    app: cardano-node-{{ $attributes.name }}
  ports:
    - protocol: TCP
      name: node
      port: {{ $attributes.port }}
      targetPort: node
      nodePort: {{ $attributes.nodePort }}
  type: NodePort
{{ end }}
{{ end }}