{{ range $attributes := .Values.nodes }}
{{ if and $attributes.enabled (eq $attributes.type "relay") }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "cardano-node-{{ $attributes.name }}"
spec:
  replicas: {{ $attributes.replicas }}
  selector:
    matchLabels:
      app: cardano-node
      name: {{ $attributes.name }}
      type: {{ $attributes.type }}
      network: {{ $.Values.network }}
  template:
    metadata:
      labels:
        app: cardano-node
        name: {{ $attributes.name }}
        type: {{ $attributes.type }}
        network: {{ $.Values.network }}
    spec:
      containers:
        - name: cardano-node
          image: "{{ $attributes.repository | default $.Values.image.repository }}:{{ $attributes.imageTag | default $.Values.image.tag }}"
          command: [ "cardano-node" ]
          args:
            - "run"
            - "--topology"
            - "/etc/config/{{ $.Values.network }}-topology.json"
            - "--database-path"
            - "/db"
            - "--socket-path"
            - "/db/node.socket"
            - "--host-addr"
            - "0.0.0.0"
            - "--port"
            - {{ $attributes.port | quote }}
            - "--config"
            - "/etc/config/{{ $.Values.network }}-config.json"
          ports:
            - name: node
              containerPort: {{ $attributes.port }}
            - name: prom
              containerPort: {{ $attributes.prometheusPort | default 12798 }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: prom
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: prom
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 10
          {{- with $.Values.resources }}
          resources:
{{ toYaml . | indent 12 }}
          {{- end }}
          volumeMounts:
            - name: config-files
              mountPath: "/etc/config/{{ $.Values.network }}-topology.json"
              subPath: "{{ $.Values.network }}-topology.json"
            - name: config-files
              mountPath: "/etc/config/{{ $.Values.network }}-config.json"
              subPath: "{{ $.Values.network }}-config.json"
            - name: "cardano-node-{{ $attributes.name }}"
              mountPath: /db
      volumes:
        - name: config-files
          configMap:
            name: node-configuration-{{ $attributes.name }}
  volumeClaimTemplates:
  - metadata:
      name: "cardano-node-{{ $attributes.name }}"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ $.Values.volumeSize }}
  strategy:
    type: Recreate
{{ else if and $attributes.enabled (eq $attributes.type "block-producer") }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "cardano-node-{{ $attributes.name }}"
spec:
  replicas: {{ $attributes.replicas }}
  selector:
    matchLabels:
      app: cardano-node
      name: {{ $attributes.name }}
      type: {{ $attributes.type }}
      network: {{ $.Values.network }}
  template:
    metadata:
      labels:
        app: cardano-node
        name: {{ $attributes.name }}
        type: {{ $attributes.type }}
        network: {{ $.Values.network }}
    spec:
      containers:
        - name: cardano-node
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          command: [ "cardano-node" ]
          args:
            - "run"
            - "--topology"
            - "/etc/config/{{ $.Values.network }}-topology.json"
            - "--database-path"
            - "/db"
            - "--socket-path"
            - "/db/node.socket"
            - "--host-addr"
            - "0.0.0.0"
            - "--port"
            - {{ $attributes.port | quote }}
            - "--config"
            - "/etc/config/{{ $.Values.network }}-config.json"
            - "--shelley-kes-key"
            - "/etc/keys/kes.skey"
            - "--shelley-vrf-key"
            - "/etc/keys/vrf.skey"
            - "--shelley-operational-certificate"
            - "/etc/keys/node.cert"
          ports:
            - name: node
              containerPort: {{ $attributes.port }}
            - name: prom
              containerPort: {{ $attributes.prometheusPort | default 12798 }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: prom
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: prom
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 10
          volumeMounts:
            - name: config-files
              mountPath: "/etc/config/{{ $.Values.network }}-topology.json"
              subPath: "{{ $.Values.network }}-topology.json"
            - name: config-files
              mountPath: "/etc/config/{{ $.Values.network }}-config.json"
              subPath: "{{ $.Values.network }}-config.json"
            - name: secret-keys
              mountPath: /etc/keys/vrf.skey
              subPath: vrf.skey
            - name: secret-keys
              mountPath: /etc/keys/kes.skey
              subPath: kes.skey
            - name: secret-keys
              mountPath: /etc/keys/node.cert
              subPath: node.cert
            - name: db
              mountPath: /db
      volumes:
        - name: config-files
          configMap:
            name: node-configuration-{{ $attributes.name }}
        - name: secret-keys
          secret:
            secretName: cardano-node-producer-secret
            defaultMode: 0400
        - name: db
          persistentVolumeClaim:
            claimName: cardano-node-{{ $attributes.name }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: network
                      operator: In
                      values:
                        - {{ $.Values.network }}
                topologyKey: "kubernetes.io/hostname"
  strategy:
    type: Recreate
{{ end }}
{{ end }}