{{ range $attributes := .Values.nodes }}
{{ if $attributes.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cardano-node-{{ $attributes.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.volumeSize }}
{{ end }}
{{ end }}
