{{ if .Values.topologyUpdater.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology-updater
      network: {{ $.Values.network }}
  template:
    metadata:
      labels:
        app: topology-updater
        network: {{ $.Values.network }}
    spec:
      containers:
        - name: topology-updater
          image: "{{ .Values.topologyUpdater.image.repository }}-{{ .Values.topologyUpdater.image.tag }}"
          args:
            - "while true; do bash /opt/cardano-node/utils/topologyUpdater.sh; sleep 3600; done"
          env:
            - name: NETWORK
              value: {{ .Values.network }}
            - name: BASE_URL
              value: "https://api.clio.one/htopology/v1"
            - name: CNODE_HOSTNAME
              value: {{ .Values.cardanoNodeHostname }}
            - name: CNODE_PORT
              value: {{ .Values.nodePort }}
          volumeMounts:
            - name: cardano-node-utils
              mountPath: "/opt/cardano-node/utils"
      volumes:
        - name: cardano-node-utils
          configMap:
            name: cardano-node-utils
  strategy:
    type: Recreate
{{ end }}