network: testnet

nodes:
  - name: iota
    type: relay
    enabled: true
    port: 3000
    replicas: 1
  - name: eta
    type: relay
    enabled: false
    port: 3000
    replicas: 1
  - name: beta
    type: block-producer
    enabled: true
    port: 3000
    replicas: 1

cardanoNodeHostname: relays-testnet2.cryptojoe.online
nodePort: 30002
