network: mainnet

nodes:
  - name: lambda
    type: relay
    enabled: true
    port: 3000
    replicas: 1
  - name: rho
    type: relay
    enabled: true
    port: 3000
    replicas: 1
  - name: alpha
    type: block-producer
    enabled: true
    port: 3000
    replicas: 1

nodePort: 30001