image:
  repository: speedwing/cardano-node
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.21.2"

volumeSize: 5Gi

resources:
  limits:
    memory: "4Gi"
    cpu: 3
  requests:
    memory: "2Gi"
    cpu: 1

#nodes:
#  - name: name of the node
#    type: [ relay | block-producer ]
#    enabled: true
#    port: 3000 [ port ]
#    imageRepository: speedwing/cardano-node
#    imageTag: 1.21.1
#
#cardanoNodeHostname: bla.online
#nodePort: 30000

topologyUpdater:
  enabled: true
  image:
    repository: "speedwing/cardano-node-utils"
    tag: "0.1-762d673"
