network: testnet

image:
  tag: "1.21.1-6-extra"

pool:
  hostName: cryptojoe.online

nodes:
  - name: tau
    type: relay
    enabled: true
    port: 3000
    replicas: 1
    topologyUpdater:
      enabled: true
  - name: phi
    type: relay
    enabled: true
    port: 3000
    replicas: 1
    topologyUpdater:
      enabled: false
  - name: omega
    type: block-producer
    enabled: true
    port: 3000
    replicas: 1

nodePort: 30000
