apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddclient-conf
  namespace: dnsutils
spec:
  encryptedData:
    ddclient.conf: AgBSMu3X3WqCuU+jTTJiLig8gxjd1exOl9ZoI8T4IYnE20M/k+8jCmkrwA9C/8RTR5Dk4o+DnRINE6PRhNzIDyx9o2eGEsW5WGZWIi1Mo9fhKBY/vO8m5prd3ZRy36kUZXkyOr7xpx9hsosHT1cDOdwcOm902x7lU3L6Y3xnoqFBjXbfDPqRyeSJvn5pYieR846ifdJajEEGcqPIVD62cM7prPBAiST2BvnT0vjCdoYgbDWDm9KIBo8m+t+/QUdrXABTAYgwW2p60lxNgwsSPQzWGbNYLu3LK8pgsC08ShOVYYA0n7KjalNlN+L1upCDFf/7740JxSo+tDoPoZ+iYukbJQtOYFjU7vUifhGgiwECqzJlCjzARo6D+81XDpV3ogoXxrOGO6u06EH1a4I3dPSWVOno1z/azRExsKLSs9WGsepD+BrP4VwQYEDm1qzEFakNPomUIHAQu3hBg0QCsxHiAiWgjKoB3Obr0WnowRFuRjFnX2UaPMNgISFANVuuhI+jEEaTuVQew9vJ9FbZYvaxLhYULh45KE67SZ8SYnI9++V05FaEx7Ym1WzPSFqunzP7nhJXTPywrzI/fNabSTjDfpf0kJlfKbc6+HB7uID9gW4bZGbRc2yG36m+Q8Es/Qut310bdEc/uVdTiREX4NwAaf/v3PGgFs90ZPmrPkzEuxnXv5XkjCu1wvIQG58DxTD+54bE1nb110eNYt2BCbwvNtxx19QBRt1Eo9FqTV0TFW+ttlqJzj17ds3Bc6+KvPNNCoaxq2uV9hJXkAZge83/z7rP/YleBa24LnRutrc7Qggi7/6TwCFceWDx15bSN1Fgu0dNYkVs0t105/qyPBayrhSIZetMKClI0MPrummTaMv91E0NUNf08nIzkX18qpf1YaiQXQ/GVmIF9OEe7iRbsZW0efRII2mCU+wu5bvpCthPna4IY1fuqFT6kJPmJ6EkU3tgd+/KDCw6uaIth5w/OvSMqFBH2oTK/tiB13ws1b6ayxDIYt0=
  template:
    metadata:
      creationTimestamp: null
      name: ddclient-conf
      namespace: dnsutils

