---
apiVersion: v1
kind: Namespace
metadata:
  name: observe
---
apiVersion: v1
kind: Namespace
metadata:
  name: dnsutils
---
apiVersion: v1
kind: Namespace
metadata:
  name: cardano-mn
---
apiVersion: v1
kind: Namespace
metadata:
  name: cardano-tn
---
apiVersion: v1
kind: Namespace
metadata:
  name: cardano-tn2
---
apiVersion: v1
kind: Namespace
metadata:
  name: cardano-tnx
