---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pvc
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/test-pvc"
