apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddclient-conf
  namespace: dnsutils
spec:
  encryptedData:
    ddclient.conf: AgCdrcF/qAssg9bih9dnpTwD/ePZZQUXJbrn6cIsQ74d0pLrVOp4FqO8uFnLvjgRYfSV4j2Iml3vkL5RYR6R5S1+mZBSIi5HysTGyhYgsgT4YBm1ngw/PLwiJ0gLL9lcakDcQGrWvRaPTa5/anr6OrFzTwjunjMMDd0KoayC8ceIZe0Y1exHkgvvtn/WAw+/+Te+pFxQPjYgLW5wZkiw5FIFrvoOHLC+XkzdzkQspiydM2ZpgUQ3VLoDexJSnQpTsy975bOxdX487ypbnyG/njgoBBcZM9o84eS9ZkYBOjx0LG+wDty8oKmvANGJq7+MRoHJzCh1W62v1gwtWFLGyqhEmSC9N3FUzt970wYDRUd/j7rxeT0aesZRb4tU7wSTBFQ36Keewd8NM9IwUIP6bT/srAsLAHmO9H5tH+NZdOeOGRvYesaweenEHWwafmokcAydRDU6BKJ2+JSOoq/d1Ee0g1smiDaijVjG16fJpLrxywrSBvh+oAT9pvSVyCfPFxhV0PD3dZ7NjZOKoLfAdeN5Zs/AcRK/wbrmx1tW9yqDt1aJ6mtGJnqxUJhkUN7pU92icgYAIGQk7gtfg8SDgz4CcvdxLiZkKE28U35nHxwZ8czjyaP3nMn/gjoKejbMlBFoXFmUXyg2jLJC34qTeNnZJ1i2cs926NDdwBwJMWbF3+KuRYoSangoWWVJNmvUgHgMO+D9260O3wUepF1JMwUQw/e+I1YXK3CMK3TRab4dBOV1JCC67CDLUjq81xhGrUCviFs80c/1VzjO4W795HYmigaJacRFPyO8YS4VjcRXrVqPFHR1jVvw/eSqeGnjBbYbaxM217Dj3gTQqKnAVIwCx/4VA8O+uIEqHKvwT6xL0e/RKtslQPTmLyoB9DCmL1Aq9DrN0xKlVHBf0sU6jjiNPjgQzwLQs2tgAiycZxCjFLLVV77b
  template:
    metadata:
      creationTimestamp: null
      name: ddclient-conf
      namespace: dnsutils

