apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddclient-conf
  namespace: dnsutils
spec:
  encryptedData:
    ddclient.conf: AgA/Zx30j2bfk/WgLcj/FoUuhvhbtB6OmkZUYtxRA09BPNU/5lHlYSumRWWMWaDY2OXfHMlGg7WnILhAKax+Cqc5FMxJ+sYm1nLsQD2EJqaoWdJrquWI6+B5ixWHrmcuc42NmJfqAmP3Ok4seRgfAuvUawrQm0lFVEceoA9wPIJontk6MV2J8XzfcA3Dl6HivWBEhb32sHlndxPnak2jzXI/5WaQGcbdAG5WBydFtdndGNGEjKQypazXYqy8p3z6SOL+91EHgVcOdEJbEpTUqsiuNf1Cs20APdVvzZZIF1nAwZJHuUhc+cJG7xDGXOGWfVfUMvp4mA8tIaKHy1GVdDYrv5M3P/VNRczi9xWGRfAGdfFhd+vguYjtx/FgF5W27GGihUL+NKzV5ZNMg3Yv+tAMgxai6QSnui5NfrFs1Mh5He9RklrKgmgcP48ev4Y5unqaoMEA63iyemV2gjD48kUi/1O5XUb/0ztb9kEyfN9beF2GqvfkMy64FrNid0XNMyz8ozREzD0Fx0GAV3XQDwgY/ECrtOieigQ5BlUBOPKwN4w/QG2yRAjnssFInR5f02AstZBtHtyzIzakFBCdvtq3Aw1OFxjnqH5iwb0l07d/hbILhgiIzQ3YgNeSYfx3WnU8ES+YhBIZN5G+QlhEX85OsAbxX6bBB4FtQjK4cHXsky6v1FQB75079wRD8c73Nq4yr7GLNLG+0DukRp2W3ibjZEB095KvbVPIHOMEd8yc4MgbiL9+QgDVTbLP9cfQK1YtFP5pm3hhn3aRlEpSBmRXHWrKh6oR42yUIsJ09T5tcboUgbS4gBE4BIIikwJU6KFcW4I067pcEzF7/0VNAfZY0JzEFr6FI+Sf+xFF1st07RFkw9e83f3mnqUbzs6FGpAqO/pzh8XTZ0faS+saEh97e5lV++R/FVGXQRMbJqP9spMKG1Qqjk2PbrMlouFg8A1C2ncFJKI9WLSStVL9lAmNeDouF+PArQN501/AU5mDMLN+lPaWxwtG4vrXhtF8r0VlUSrRRA0FGQUYBafKRnvrCcYuUc2uDAa6eXH680g=
  template:
    metadata:
      creationTimestamp: null
      name: ddclient-conf
      namespace: dnsutils

